baseurl = "http://telepathy.freedesktop.org/"
languageCode = "en-us"
title = "Telepathy"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = false
# Enable Google Analytics by entering your tracking id
#googleAnalytics = ""

[params]
    # General information
    #author = ""
    #description = ""
    #copyright = "The Telepathy team, CC-BY 4.0"

    # Repository
    #provider = "github"
    #repo_url = "http://cgit.freedesktop.org/telepathy"

    version = ""
    logo = "images/Telepathy.png"
    favicon = ""

    permalink = "#"

    # Custom assets
    custom_css = ["stylesheets/telepathy.css"]
    custom_js  = []

    # Syntax highlighting theme
    highlight_css  = ""

[params.palette]
    primary = "indigo"
    accent  = "orange"

[params.font]
    text = "Ubuntu"
    code = "Ubuntu Mono"


[social]
    twitter = ""
    github  = ""

[taxonomies]
    category   = "categories"

[[menu.main]]
    name   = "About"
    url    = "about/"
    weight = 10

# [[menu.main]]
#   name   = "News"
#   url    = "news/"
#   weight = 30

[[menu.main]]
    name   = "Components"
    url       = "components/"
    weight = 30

[[menu.main]]
    name   = "Releases"
    url       = "components/releases/"
    weight = 40

[[menu.main]]
    name = "Documentation"
    url   = "components/documentation/"
    weight = 45

[[menu.main]]
    name   = "Resources"
    weight = 70
    url       = "resources/"

[[menu.community]]
    name = "IRC channel"
    url = "community/chat/"
    weight = 1

[[menu.community]]
    name = "Mailing List"
    url = "community/mailing_list/"
    weight = 2

[[menu.community]]
    name = "Bug tracker"
    url = "community/bug_tracker/"
    weight = 3

[blackfriday]
    smartypants	= true
    fractions = true
    smartDashes = true
    plainIDAnchors = true
